// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserActivityEvent_Type int32

const (
	UserActivityEvent_UNSPECIFIED UserActivityEvent_Type = 0
	UserActivityEvent_ONLINE      UserActivityEvent_Type = 1
	UserActivityEvent_OFFLINE     UserActivityEvent_Type = 2
	UserActivityEvent_HEARD       UserActivityEvent_Type = 3
	UserActivityEvent_ENTER_ROOM  UserActivityEvent_Type = 4
	UserActivityEvent_LEAVE_ROOM  UserActivityEvent_Type = 5
)

var UserActivityEvent_Type_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ONLINE",
	2: "OFFLINE",
	3: "HEARD",
	4: "ENTER_ROOM",
	5: "LEAVE_ROOM",
}

var UserActivityEvent_Type_value = map[string]int32{
	"UNSPECIFIED": 0,
	"ONLINE":      1,
	"OFFLINE":     2,
	"HEARD":       3,
	"ENTER_ROOM":  4,
	"LEAVE_ROOM":  5,
}

func (x UserActivityEvent_Type) String() string {
	return proto.EnumName(UserActivityEvent_Type_name, int32(x))
}

func (UserActivityEvent_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2, 0}
}

// Event is the asynchronous message using Go-Micro's message broker interface.
// refer to Comet.onEvent
type Event struct {
	// The unique user identity
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The room identity
	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	// The server-sent event goes through the downlink to the client.
	Evt                  string   `protobuf:"bytes,3,opt,name=evt,proto3" json:"evt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Event) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Event) GetEvt() string {
	if m != nil {
		return m.Evt
	}
	return ""
}

// Message is the general content predefined by comet for server-sent event.
// It is stringified to JSON and then assigned to `string evt`.
type Message struct {
	// A optional string identifying the server that generates event.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// A string identifying the type of event.
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// The data field for the message.
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// The event ID.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// The time this event happens. It is the number of nanoseconds elapsed since January 1, 1970 UTC.
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Message) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// UserActivityEvent is generated by comet to indicate the user activity.
type UserActivityEvent struct {
	Type                 UserActivityEvent_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.UserActivityEvent_Type" json:"type,omitempty"`
	Uid                  string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Rid                  string                 `protobuf:"bytes,3,opt,name=rid,proto3" json:"rid,omitempty"`
	Time                 int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserActivityEvent) Reset()         { *m = UserActivityEvent{} }
func (m *UserActivityEvent) String() string { return proto.CompactTextString(m) }
func (*UserActivityEvent) ProtoMessage()    {}
func (*UserActivityEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *UserActivityEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivityEvent.Unmarshal(m, b)
}
func (m *UserActivityEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivityEvent.Marshal(b, m, deterministic)
}
func (m *UserActivityEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivityEvent.Merge(m, src)
}
func (m *UserActivityEvent) XXX_Size() int {
	return xxx_messageInfo_UserActivityEvent.Size(m)
}
func (m *UserActivityEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivityEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivityEvent proto.InternalMessageInfo

func (m *UserActivityEvent) GetType() UserActivityEvent_Type {
	if m != nil {
		return m.Type
	}
	return UserActivityEvent_UNSPECIFIED
}

func (m *UserActivityEvent) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserActivityEvent) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *UserActivityEvent) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterEnum("proto.UserActivityEvent_Type", UserActivityEvent_Type_name, UserActivityEvent_Type_value)
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*UserActivityEvent)(nil), "proto.UserActivityEvent")
}

func init() {
	proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8)
}

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x4f, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x1f, 0xdb, 0xd2, 0x57, 0xa8, 0xf1, 0x21, 0x92, 0x8b, 0x50, 0x7a, 0xea, 0x29, 0xa0,
	0x9e, 0x3d, 0x04, 0xbb, 0xc1, 0x40, 0x9b, 0xc8, 0xda, 0x7a, 0xf1, 0x20, 0xd1, 0x3c, 0x64, 0x0f,
	0x9a, 0xb0, 0x59, 0x03, 0xf9, 0xad, 0xfe, 0x19, 0xd9, 0xdd, 0x88, 0x87, 0x7a, 0xd9, 0x9d, 0x19,
	0x86, 0x79, 0x33, 0x30, 0x6f, 0x55, 0xa3, 0x9b, 0xc4, 0xbe, 0xc8, 0xec, 0xb7, 0xba, 0x05, 0xc6,
	0x7b, 0xfa, 0xd4, 0x18, 0x41, 0xf0, 0x25, 0xeb, 0xd8, 0x5b, 0x7a, 0xeb, 0x99, 0x30, 0xd0, 0x28,
	0x4a, 0xd6, 0xb1, 0xef, 0x14, 0xe5, 0x14, 0xea, 0x75, 0x1c, 0x38, 0x85, 0x7a, 0xbd, 0x6a, 0x60,
	0xba, 0xa3, 0xae, 0xab, 0xde, 0x09, 0x2f, 0x60, 0xd2, 0x91, 0xea, 0x49, 0x8d, 0x19, 0x23, 0xc3,
	0x73, 0x60, 0x64, 0x2e, 0x8c, 0x41, 0x8e, 0x20, 0x42, 0x58, 0x57, 0xba, 0x1a, 0xb3, 0x2c, 0xc6,
	0x05, 0xf8, 0xb2, 0x8e, 0x43, 0xab, 0xf8, 0xb2, 0x36, 0x1e, 0x2d, 0x3f, 0x28, 0x66, 0x4b, 0x6f,
	0x1d, 0x08, 0x8b, 0x57, 0xdf, 0x1e, 0x9c, 0x1d, 0x3a, 0x52, 0xe9, 0x9b, 0x96, 0xbd, 0xd4, 0x83,
	0x2b, 0x7f, 0x05, 0xa1, 0x1e, 0x5a, 0xb2, 0x97, 0x17, 0xd7, 0x97, 0x6e, 0x62, 0x72, 0xe4, 0x4b,
	0xf6, 0x43, 0x4b, 0xc2, 0x5a, 0x7f, 0xf7, 0xfa, 0x47, 0x7b, 0x83, 0xbf, 0xbd, 0xff, 0x15, 0x78,
	0x86, 0xd0, 0xa4, 0xe0, 0x29, 0xcc, 0x0f, 0xc5, 0xe3, 0x03, 0xbf, 0xcb, 0xb3, 0x9c, 0x6f, 0xa2,
	0x13, 0x04, 0x98, 0x94, 0xc5, 0x36, 0x2f, 0x78, 0xe4, 0xe1, 0x1c, 0xa6, 0x65, 0x96, 0x59, 0xe2,
	0xe3, 0x0c, 0xd8, 0x3d, 0x4f, 0xc5, 0x26, 0x0a, 0x70, 0x01, 0xc0, 0x8b, 0x3d, 0x17, 0x2f, 0xa2,
	0x2c, 0x77, 0x51, 0x68, 0xf8, 0x96, 0xa7, 0x4f, 0xdc, 0x71, 0xf6, 0x3a, 0xb1, 0xc5, 0x6f, 0x7e,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x02, 0x63, 0x5e, 0xf7, 0xaa, 0x01, 0x00, 0x00,
}
