// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Event is the asynchronous message using Go-Micro's message broker interface.
// refer to Comet.onEvent
type Event struct {
	// The unique user identity
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The room identity
	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	// The server-sent event goes through the downlink to the client.
	Evt                  string   `protobuf:"bytes,3,opt,name=evt,proto3" json:"evt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Event) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Event) GetEvt() string {
	if m != nil {
		return m.Evt
	}
	return ""
}

// Message is the general content predefined by comet for server-sent event.
// It is stringified to JSON and then assigned to `string evt`.
type Message struct {
	// A optional string identifying the server that generates event.
	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// A string identifying the type of event.
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// The data field for the message.
	Data string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// The event ID.
	Id string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// The time this event happens. It is the number of nanoseconds elapsed since January 1, 1970 UTC.
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Message) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Message) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Message) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Message) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() {
	proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8)
}

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0x8e, 0x31, 0xcb, 0x02, 0x31,
	0x0c, 0x86, 0xb9, 0xf6, 0x7a, 0x1f, 0x5f, 0x04, 0x91, 0x20, 0xd2, 0xf1, 0xb8, 0xe9, 0x26, 0x17,
	0x67, 0x47, 0x47, 0x97, 0xfb, 0x07, 0x95, 0x06, 0xe9, 0xa0, 0x95, 0x36, 0xf6, 0xf7, 0x4b, 0xd3,
	0x2e, 0xed, 0xfb, 0x3e, 0x84, 0x27, 0x81, 0xdd, 0x27, 0x45, 0x8e, 0x67, 0x79, 0xd1, 0xc8, 0xb7,
	0x5c, 0xc1, 0xdc, 0x0a, 0xbd, 0x19, 0x0f, 0xa0, 0xbf, 0xc1, 0xdb, 0x61, 0x1e, 0xd6, 0xff, 0xad,
	0xc6, 0x4a, 0x52, 0xf0, 0x56, 0x35, 0x92, 0x1a, 0xa1, 0xc2, 0x56, 0x37, 0x42, 0x85, 0x97, 0x08,
	0x7f, 0x77, 0xca, 0xd9, 0x3d, 0x09, 0x4f, 0x30, 0x65, 0x4a, 0x85, 0x52, 0x77, 0xf4, 0x86, 0x47,
	0x30, 0x54, 0x37, 0x74, 0x51, 0x2b, 0x88, 0x30, 0x7a, 0xc7, 0xae, 0xbb, 0x24, 0xe3, 0x1e, 0x54,
	0xf0, 0x76, 0x14, 0xa2, 0x82, 0xaf, 0x33, 0x1c, 0x5e, 0x64, 0xcd, 0x3c, 0xac, 0x7a, 0x93, 0xfc,
	0x98, 0xe4, 0xec, 0xcb, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xf5, 0xe2, 0xed, 0xcc, 0x00, 0x00,
	0x00,
}
