// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: liveroom.proto

package liveroom

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Room service

func NewRoomEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Room service

type RoomService interface {
	// 在聊天室里，发送消息
	Send(ctx context.Context, in *SendReq, opts ...client.CallOption) (*SendRes, error)
	// 收取聊天室里的未读消息
	Recv(ctx context.Context, in *RecvReq, opts ...client.CallOption) (*RecvRes, error)
}

type roomService struct {
	c    client.Client
	name string
}

func NewRoomService(name string, c client.Client) RoomService {
	return &roomService{
		c:    c,
		name: name,
	}
}

func (c *roomService) Send(ctx context.Context, in *SendReq, opts ...client.CallOption) (*SendRes, error) {
	req := c.c.NewRequest(c.name, "Room.Send", in)
	out := new(SendRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roomService) Recv(ctx context.Context, in *RecvReq, opts ...client.CallOption) (*RecvRes, error) {
	req := c.c.NewRequest(c.name, "Room.Recv", in)
	out := new(RecvRes)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Room service

type RoomHandler interface {
	// 在聊天室里，发送消息
	Send(context.Context, *SendReq, *SendRes) error
	// 收取聊天室里的未读消息
	Recv(context.Context, *RecvReq, *RecvRes) error
}

func RegisterRoomHandler(s server.Server, hdlr RoomHandler, opts ...server.HandlerOption) error {
	type room interface {
		Send(ctx context.Context, in *SendReq, out *SendRes) error
		Recv(ctx context.Context, in *RecvReq, out *RecvRes) error
	}
	type Room struct {
		room
	}
	h := &roomHandler{hdlr}
	return s.Handle(s.NewHandler(&Room{h}, opts...))
}

type roomHandler struct {
	RoomHandler
}

func (h *roomHandler) Send(ctx context.Context, in *SendReq, out *SendRes) error {
	return h.RoomHandler.Send(ctx, in, out)
}

func (h *roomHandler) Recv(ctx context.Context, in *RecvReq, out *RecvRes) error {
	return h.RoomHandler.Recv(ctx, in, out)
}
