// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sequence.proto

package sequence

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NextReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextReq) Reset()         { *m = NextReq{} }
func (m *NextReq) String() string { return proto.CompactTextString(m) }
func (*NextReq) ProtoMessage()    {}
func (*NextReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e97b888ecada2421, []int{0}
}

func (m *NextReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextReq.Unmarshal(m, b)
}
func (m *NextReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextReq.Marshal(b, m, deterministic)
}
func (m *NextReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextReq.Merge(m, src)
}
func (m *NextReq) XXX_Size() int {
	return xxx_messageInfo_NextReq.Size(m)
}
func (m *NextReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NextReq.DiscardUnknown(m)
}

var xxx_messageInfo_NextReq proto.InternalMessageInfo

func (m *NextReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NextRes struct {
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextRes) Reset()         { *m = NextRes{} }
func (m *NextRes) String() string { return proto.CompactTextString(m) }
func (*NextRes) ProtoMessage()    {}
func (*NextRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e97b888ecada2421, []int{1}
}

func (m *NextRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextRes.Unmarshal(m, b)
}
func (m *NextRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextRes.Marshal(b, m, deterministic)
}
func (m *NextRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextRes.Merge(m, src)
}
func (m *NextRes) XXX_Size() int {
	return xxx_messageInfo_NextRes.Size(m)
}
func (m *NextRes) XXX_DiscardUnknown() {
	xxx_messageInfo_NextRes.DiscardUnknown(m)
}

var xxx_messageInfo_NextRes proto.InternalMessageInfo

func (m *NextRes) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type MaxReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxReq) Reset()         { *m = MaxReq{} }
func (m *MaxReq) String() string { return proto.CompactTextString(m) }
func (*MaxReq) ProtoMessage()    {}
func (*MaxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e97b888ecada2421, []int{2}
}

func (m *MaxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxReq.Unmarshal(m, b)
}
func (m *MaxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxReq.Marshal(b, m, deterministic)
}
func (m *MaxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxReq.Merge(m, src)
}
func (m *MaxReq) XXX_Size() int {
	return xxx_messageInfo_MaxReq.Size(m)
}
func (m *MaxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxReq.DiscardUnknown(m)
}

var xxx_messageInfo_MaxReq proto.InternalMessageInfo

func (m *MaxReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MaxRes struct {
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaxRes) Reset()         { *m = MaxRes{} }
func (m *MaxRes) String() string { return proto.CompactTextString(m) }
func (*MaxRes) ProtoMessage()    {}
func (*MaxRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e97b888ecada2421, []int{3}
}

func (m *MaxRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaxRes.Unmarshal(m, b)
}
func (m *MaxRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaxRes.Marshal(b, m, deterministic)
}
func (m *MaxRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaxRes.Merge(m, src)
}
func (m *MaxRes) XXX_Size() int {
	return xxx_messageInfo_MaxRes.Size(m)
}
func (m *MaxRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MaxRes.DiscardUnknown(m)
}

var xxx_messageInfo_MaxRes proto.InternalMessageInfo

func (m *MaxRes) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*NextReq)(nil), "sequence.NextReq")
	proto.RegisterType((*NextRes)(nil), "sequence.NextRes")
	proto.RegisterType((*MaxReq)(nil), "sequence.MaxReq")
	proto.RegisterType((*MaxRes)(nil), "sequence.MaxRes")
}

func init() {
	proto.RegisterFile("sequence.proto", fileDescriptor_e97b888ecada2421)
}

var fileDescriptor_e97b888ecada2421 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4e, 0x2d, 0x2c,
	0x4d, 0xcd, 0x4b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x64,
	0xb9, 0xd8, 0xfd, 0x52, 0x2b, 0x4a, 0x82, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x79, 0x98, 0x74, 0xb1, 0x90,
	0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x84,
	0xa3, 0x24, 0xc3, 0xc5, 0xe6, 0x9b, 0x58, 0x81, 0x4b, 0xbb, 0x1c, 0x54, 0x16, 0x87, 0x6e, 0xa3,
	0x64, 0x2e, 0x8e, 0x60, 0xa8, 0x4b, 0x84, 0x74, 0xb8, 0x58, 0x40, 0x56, 0x09, 0x09, 0xea, 0xc1,
	0x1d, 0x0b, 0x75, 0x99, 0x14, 0x86, 0x50, 0xb1, 0x90, 0x26, 0x17, 0xb3, 0x6f, 0x62, 0x85, 0x90,
	0x00, 0x42, 0x06, 0xe2, 0x0c, 0x29, 0x74, 0x91, 0xe2, 0x24, 0x36, 0xb0, 0x9f, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x3e, 0x9f, 0x45, 0x26, 0x05, 0x01, 0x00, 0x00,
}
