// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comet.proto

package comet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServerPush_Type int32

const (
	ServerPush_HEARTBEAT    ServerPush_Type = 0
	ServerPush_PUBLISH_NOTE ServerPush_Type = 1
)

var ServerPush_Type_name = map[int32]string{
	0: "HEARTBEAT",
	1: "PUBLISH_NOTE",
}

var ServerPush_Type_value = map[string]int32{
	"HEARTBEAT":    0,
	"PUBLISH_NOTE": 1,
}

func (x ServerPush_Type) String() string {
	return proto.EnumName(ServerPush_Type_name, int32(x))
}

func (ServerPush_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{1, 0}
}

type Heartbeat struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ServerPush struct {
	T                    ServerPush_Type `protobuf:"varint,1,opt,name=t,proto3,enum=comet.ServerPush_Type" json:"t,omitempty"`
	PublishNote          *PublishNote    `protobuf:"bytes,2,opt,name=publish_note,json=publishNote,proto3" json:"publish_note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServerPush) Reset()         { *m = ServerPush{} }
func (m *ServerPush) String() string { return proto.CompactTextString(m) }
func (*ServerPush) ProtoMessage()    {}
func (*ServerPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{1}
}

func (m *ServerPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPush.Unmarshal(m, b)
}
func (m *ServerPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPush.Marshal(b, m, deterministic)
}
func (m *ServerPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPush.Merge(m, src)
}
func (m *ServerPush) XXX_Size() int {
	return xxx_messageInfo_ServerPush.Size(m)
}
func (m *ServerPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPush.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPush proto.InternalMessageInfo

func (m *ServerPush) GetT() ServerPush_Type {
	if m != nil {
		return m.T
	}
	return ServerPush_HEARTBEAT
}

func (m *ServerPush) GetPublishNote() *PublishNote {
	if m != nil {
		return m.PublishNote
	}
	return nil
}

type PublishNote struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishNote) Reset()         { *m = PublishNote{} }
func (m *PublishNote) String() string { return proto.CompactTextString(m) }
func (*PublishNote) ProtoMessage()    {}
func (*PublishNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{2}
}

func (m *PublishNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishNote.Unmarshal(m, b)
}
func (m *PublishNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishNote.Marshal(b, m, deterministic)
}
func (m *PublishNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishNote.Merge(m, src)
}
func (m *PublishNote) XXX_Size() int {
	return xxx_messageInfo_PublishNote.Size(m)
}
func (m *PublishNote) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishNote.DiscardUnknown(m)
}

var xxx_messageInfo_PublishNote proto.InternalMessageInfo

func (m *PublishNote) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishNote) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PublishReq struct {
	PublishNote          *PublishNote `protobuf:"bytes,1,opt,name=publish_note,json=publishNote,proto3" json:"publish_note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PublishReq) Reset()         { *m = PublishReq{} }
func (m *PublishReq) String() string { return proto.CompactTextString(m) }
func (*PublishReq) ProtoMessage()    {}
func (*PublishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{3}
}

func (m *PublishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReq.Unmarshal(m, b)
}
func (m *PublishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReq.Marshal(b, m, deterministic)
}
func (m *PublishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReq.Merge(m, src)
}
func (m *PublishReq) XXX_Size() int {
	return xxx_messageInfo_PublishReq.Size(m)
}
func (m *PublishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReq proto.InternalMessageInfo

func (m *PublishReq) GetPublishNote() *PublishNote {
	if m != nil {
		return m.PublishNote
	}
	return nil
}

type PublishRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRes) Reset()         { *m = PublishRes{} }
func (m *PublishRes) String() string { return proto.CompactTextString(m) }
func (*PublishRes) ProtoMessage()    {}
func (*PublishRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{4}
}

func (m *PublishRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRes.Unmarshal(m, b)
}
func (m *PublishRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRes.Marshal(b, m, deterministic)
}
func (m *PublishRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRes.Merge(m, src)
}
func (m *PublishRes) XXX_Size() int {
	return xxx_messageInfo_PublishRes.Size(m)
}
func (m *PublishRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRes.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRes proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("comet.ServerPush_Type", ServerPush_Type_name, ServerPush_Type_value)
	proto.RegisterType((*Heartbeat)(nil), "comet.Heartbeat")
	proto.RegisterType((*ServerPush)(nil), "comet.ServerPush")
	proto.RegisterType((*PublishNote)(nil), "comet.PublishNote")
	proto.RegisterType((*PublishReq)(nil), "comet.PublishReq")
	proto.RegisterType((*PublishRes)(nil), "comet.PublishRes")
}

func init() {
	proto.RegisterFile("comet.proto", fileDescriptor_ac08d4044ac8a660)
}

var fileDescriptor_ac08d4044ac8a660 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xff, 0xfb, 0xa7, 0x55, 0x32, 0x89, 0x12, 0x07, 0x91, 0xe2, 0xa9, 0x06, 0xc1, 0x9c,
	0xa2, 0x44, 0xc5, 0x73, 0x5b, 0x02, 0x11, 0xa4, 0x86, 0x4d, 0x3c, 0x97, 0x26, 0x0c, 0x34, 0xa8,
	0xd9, 0x6d, 0x32, 0x11, 0xfd, 0x1a, 0x7e, 0x62, 0x69, 0x12, 0x9a, 0x4a, 0x2f, 0xde, 0xf2, 0xe6,
	0xcd, 0xfb, 0xe5, 0xb1, 0x03, 0x66, 0xa6, 0xde, 0x89, 0x3d, 0x5d, 0x2a, 0x56, 0x38, 0x6c, 0x84,
	0x73, 0x01, 0x46, 0x48, 0xcb, 0x92, 0x53, 0x5a, 0x32, 0x9e, 0xc2, 0x90, 0xd5, 0x2b, 0x15, 0x23,
	0x31, 0x16, 0xae, 0x21, 0x5b, 0xe1, 0x7c, 0x0b, 0x80, 0x98, 0xca, 0x0f, 0x2a, 0xa3, 0xba, 0x5a,
	0xe1, 0x25, 0x08, 0x6e, 0x16, 0x8e, 0xfd, 0x33, 0xaf, 0x25, 0xf6, 0xae, 0x97, 0x7c, 0x69, 0x92,
	0x82, 0xf1, 0x1e, 0x2c, 0x5d, 0xa7, 0x6f, 0x79, 0xb5, 0x5a, 0x14, 0x8a, 0x69, 0xf4, 0x7f, 0x2c,
	0x5c, 0xd3, 0xc7, 0x2e, 0x10, 0xb5, 0xd6, 0x5c, 0x31, 0x49, 0x53, 0xf7, 0xc2, 0xb9, 0x82, 0xc1,
	0x86, 0x80, 0x47, 0x60, 0x84, 0xc1, 0x44, 0x26, 0xd3, 0x60, 0x92, 0xd8, 0xff, 0xd0, 0x06, 0x2b,
	0x7a, 0x99, 0x3e, 0x3d, 0xc6, 0xe1, 0x62, 0xfe, 0x9c, 0x04, 0xb6, 0x70, 0x1e, 0xc0, 0xdc, 0x81,
	0xb4, 0xcd, 0x75, 0x9e, 0xf5, 0xcd, 0x75, 0x9e, 0x21, 0xc2, 0x80, 0xe9, 0x93, 0x9b, 0x9f, 0x1b,
	0xb2, 0xf9, 0x76, 0x66, 0x00, 0x5d, 0x50, 0xd2, 0x7a, 0xaf, 0xa6, 0xf8, 0x5b, 0x4d, 0x6b, 0x07,
	0x52, 0xf9, 0x05, 0x0c, 0x67, 0x9b, 0x7d, 0xbc, 0x86, 0xc3, 0x6e, 0x8c, 0x27, 0xbf, 0x11, 0x92,
	0xd6, 0xe7, 0x7b, 0xa3, 0x0a, 0xef, 0xc0, 0x88, 0xeb, 0xb4, 0xca, 0xca, 0x3c, 0x25, 0xb4, 0x3b,
	0x7f, 0x7b, 0x8f, 0x6d, 0xa2, 0x7f, 0x5f, 0x57, 0xdc, 0x88, 0xf4, 0xa0, 0xb9, 0xe0, 0xed, 0x4f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xf4, 0x8b, 0xc0, 0xd0, 0x01, 0x00, 0x00,
}
