// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comet.proto

package comet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The type of packet that is transferring on the wire of uplink and downlink
type Packet int32

const (
	// Heartbeat is sent on downlink and uplink, to keep the persistent connection alive
	Packet_HB Packet = 0
	// Auth is sent on uplink as the first message for Comet.Subscribe
	Packet_AUTH Packet = 1
	// JoinRoom is sent on uplink to join the specified room. JOIN can be sent together with AUTH,
	// which means connect to comet and join the specified room immediately. A client follows
	// only one room at a time. If a client is already in a room, JOIN a different room implies
	// quitting the last room where the client stays; JOIN the same room is a no-op. A connected
	// client is always considered in the world in spite of maybe in a room.
	Packet_JOIN Packet = 2
	// ServerPush is sent on downlink to push event to client
	Packet_PUSH Packet = 3
)

var Packet_name = map[int32]string{
	0: "HB",
	1: "AUTH",
	2: "JOIN",
	3: "PUSH",
}

var Packet_value = map[string]int32{
	"HB":   0,
	"AUTH": 1,
	"JOIN": 2,
	"PUSH": 3,
}

func (x Packet) String() string {
	return proto.EnumName(Packet_name, int32(x))
}

func (Packet) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{0}
}

type PublishReq struct {
	// The unique user identity.
	// Please note if an end-user has multiple terminals such as a phone, a pad, and a desktop,
	// every terminal should use a unique identity if these devices are treated differently.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The server-sent event goes through the downlink to the client.
	// Its content is opaque, which means what is published here reaches client unmodified.
	// Only the concrete business can explain this event.
	Evt                  string   `protobuf:"bytes,2,opt,name=evt,proto3" json:"evt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishReq) Reset()         { *m = PublishReq{} }
func (m *PublishReq) String() string { return proto.CompactTextString(m) }
func (*PublishReq) ProtoMessage()    {}
func (*PublishReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{0}
}

func (m *PublishReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReq.Unmarshal(m, b)
}
func (m *PublishReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReq.Marshal(b, m, deterministic)
}
func (m *PublishReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReq.Merge(m, src)
}
func (m *PublishReq) XXX_Size() int {
	return xxx_messageInfo_PublishReq.Size(m)
}
func (m *PublishReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReq.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReq proto.InternalMessageInfo

func (m *PublishReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *PublishReq) GetEvt() string {
	if m != nil {
		return m.Evt
	}
	return ""
}

type PublishRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRes) Reset()         { *m = PublishRes{} }
func (m *PublishRes) String() string { return proto.CompactTextString(m) }
func (*PublishRes) ProtoMessage()    {}
func (*PublishRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{1}
}

func (m *PublishRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRes.Unmarshal(m, b)
}
func (m *PublishRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRes.Marshal(b, m, deterministic)
}
func (m *PublishRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRes.Merge(m, src)
}
func (m *PublishRes) XXX_Size() int {
	return xxx_messageInfo_PublishRes.Size(m)
}
func (m *PublishRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRes.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRes proto.InternalMessageInfo

type BroadcastReq struct {
	// The room identity, default (empty) to do a world broadcast, which means all the clients on
	// this comet instance are published with the event. Otherwise, the broadcast is delivered to
	// the clients within the room.
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// The server-sent event goes through the downlink to the client.
	// Its content is opaque, which means what is published here reaches client unmodified.
	// Only the concrete business can explain this event.
	Evt                  string   `protobuf:"bytes,2,opt,name=evt,proto3" json:"evt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReq) Reset()         { *m = BroadcastReq{} }
func (m *BroadcastReq) String() string { return proto.CompactTextString(m) }
func (*BroadcastReq) ProtoMessage()    {}
func (*BroadcastReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{2}
}

func (m *BroadcastReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReq.Unmarshal(m, b)
}
func (m *BroadcastReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReq.Marshal(b, m, deterministic)
}
func (m *BroadcastReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReq.Merge(m, src)
}
func (m *BroadcastReq) XXX_Size() int {
	return xxx_messageInfo_BroadcastReq.Size(m)
}
func (m *BroadcastReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReq.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReq proto.InternalMessageInfo

func (m *BroadcastReq) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *BroadcastReq) GetEvt() string {
	if m != nil {
		return m.Evt
	}
	return ""
}

type BroadcastRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRes) Reset()         { *m = BroadcastRes{} }
func (m *BroadcastRes) String() string { return proto.CompactTextString(m) }
func (*BroadcastRes) ProtoMessage()    {}
func (*BroadcastRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{3}
}

func (m *BroadcastRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRes.Unmarshal(m, b)
}
func (m *BroadcastRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRes.Marshal(b, m, deterministic)
}
func (m *BroadcastRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRes.Merge(m, src)
}
func (m *BroadcastRes) XXX_Size() int {
	return xxx_messageInfo_BroadcastRes.Size(m)
}
func (m *BroadcastRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRes.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRes proto.InternalMessageInfo

type DumpSessionReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpSessionReq) Reset()         { *m = DumpSessionReq{} }
func (m *DumpSessionReq) String() string { return proto.CompactTextString(m) }
func (*DumpSessionReq) ProtoMessage()    {}
func (*DumpSessionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{4}
}

func (m *DumpSessionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpSessionReq.Unmarshal(m, b)
}
func (m *DumpSessionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpSessionReq.Marshal(b, m, deterministic)
}
func (m *DumpSessionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpSessionReq.Merge(m, src)
}
func (m *DumpSessionReq) XXX_Size() int {
	return xxx_messageInfo_DumpSessionReq.Size(m)
}
func (m *DumpSessionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpSessionReq.DiscardUnknown(m)
}

var xxx_messageInfo_DumpSessionReq proto.InternalMessageInfo

type DumpSessionRes struct {
	// All the sessions in the world in this comet instance
	World []*Session `protobuf:"bytes,1,rep,name=world,proto3" json:"world,omitempty"`
	// All the rooms in this comet instance
	Rooms                []*Room  `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpSessionRes) Reset()         { *m = DumpSessionRes{} }
func (m *DumpSessionRes) String() string { return proto.CompactTextString(m) }
func (*DumpSessionRes) ProtoMessage()    {}
func (*DumpSessionRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{5}
}

func (m *DumpSessionRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpSessionRes.Unmarshal(m, b)
}
func (m *DumpSessionRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpSessionRes.Marshal(b, m, deterministic)
}
func (m *DumpSessionRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpSessionRes.Merge(m, src)
}
func (m *DumpSessionRes) XXX_Size() int {
	return xxx_messageInfo_DumpSessionRes.Size(m)
}
func (m *DumpSessionRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpSessionRes.DiscardUnknown(m)
}

var xxx_messageInfo_DumpSessionRes proto.InternalMessageInfo

func (m *DumpSessionRes) GetWorld() []*Session {
	if m != nil {
		return m.World
	}
	return nil
}

func (m *DumpSessionRes) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

// Room is a (virtual) place where session gathers.
type Room struct {
	// The room identity
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// All the sessions in this room.
	Room                 []*Session `protobuf:"bytes,2,rep,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{6}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Room) GetRoom() []*Session {
	if m != nil {
		return m.Room
	}
	return nil
}

// Session is a user's session. It is created when a client subscribes to this comet, and
// destroyed when the client disconnected.
type Session struct {
	// The unique user identity
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// The room identity
	Rid string `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	// When is the session created
	Birth                string   `protobuf:"bytes,3,opt,name=birth,proto3" json:"birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{7}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Session) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Session) GetBirth() string {
	if m != nil {
		return m.Birth
	}
	return ""
}

type Uplink struct {
	// type is used to differentiate what this uplink message is
	Type                 Packet     `protobuf:"varint,1,opt,name=type,proto3,enum=comet.Packet" json:"type,omitempty"`
	Hb                   *Heartbeat `protobuf:"bytes,2,opt,name=hb,proto3" json:"hb,omitempty"`
	Auth                 *Auth      `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Join                 *JoinRoom  `protobuf:"bytes,4,opt,name=join,proto3" json:"join,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Uplink) Reset()         { *m = Uplink{} }
func (m *Uplink) String() string { return proto.CompactTextString(m) }
func (*Uplink) ProtoMessage()    {}
func (*Uplink) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{8}
}

func (m *Uplink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uplink.Unmarshal(m, b)
}
func (m *Uplink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uplink.Marshal(b, m, deterministic)
}
func (m *Uplink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uplink.Merge(m, src)
}
func (m *Uplink) XXX_Size() int {
	return xxx_messageInfo_Uplink.Size(m)
}
func (m *Uplink) XXX_DiscardUnknown() {
	xxx_messageInfo_Uplink.DiscardUnknown(m)
}

var xxx_messageInfo_Uplink proto.InternalMessageInfo

func (m *Uplink) GetType() Packet {
	if m != nil {
		return m.Type
	}
	return Packet_HB
}

func (m *Uplink) GetHb() *Heartbeat {
	if m != nil {
		return m.Hb
	}
	return nil
}

func (m *Uplink) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *Uplink) GetJoin() *JoinRoom {
	if m != nil {
		return m.Join
	}
	return nil
}

type Downlink struct {
	// type is used to differentiate what this downlink message is
	Type                 Packet      `protobuf:"varint,1,opt,name=type,proto3,enum=comet.Packet" json:"type,omitempty"`
	Hb                   *Heartbeat  `protobuf:"bytes,2,opt,name=hb,proto3" json:"hb,omitempty"`
	Push                 *ServerPush `protobuf:"bytes,3,opt,name=push,proto3" json:"push,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Downlink) Reset()         { *m = Downlink{} }
func (m *Downlink) String() string { return proto.CompactTextString(m) }
func (*Downlink) ProtoMessage()    {}
func (*Downlink) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{9}
}

func (m *Downlink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Downlink.Unmarshal(m, b)
}
func (m *Downlink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Downlink.Marshal(b, m, deterministic)
}
func (m *Downlink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Downlink.Merge(m, src)
}
func (m *Downlink) XXX_Size() int {
	return xxx_messageInfo_Downlink.Size(m)
}
func (m *Downlink) XXX_DiscardUnknown() {
	xxx_messageInfo_Downlink.DiscardUnknown(m)
}

var xxx_messageInfo_Downlink proto.InternalMessageInfo

func (m *Downlink) GetType() Packet {
	if m != nil {
		return m.Type
	}
	return Packet_HB
}

func (m *Downlink) GetHb() *Heartbeat {
	if m != nil {
		return m.Hb
	}
	return nil
}

func (m *Downlink) GetPush() *ServerPush {
	if m != nil {
		return m.Push
	}
	return nil
}

type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{10}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

type Auth struct {
	// Usually a JWT is used. Comet.Subscribe extracts user's account information from this token.
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{11}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type JoinRoom struct {
	// The room identity, default (empty) to quit any room and stay only in the world.
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRoom) Reset()         { *m = JoinRoom{} }
func (m *JoinRoom) String() string { return proto.CompactTextString(m) }
func (*JoinRoom) ProtoMessage()    {}
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{12}
}

func (m *JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoom.Unmarshal(m, b)
}
func (m *JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoom.Marshal(b, m, deterministic)
}
func (m *JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoom.Merge(m, src)
}
func (m *JoinRoom) XXX_Size() int {
	return xxx_messageInfo_JoinRoom.Size(m)
}
func (m *JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoom proto.InternalMessageInfo

func (m *JoinRoom) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

type ServerPush struct {
	// The server-sent event goes through the downlink to the client.
	// Its content is opaque, which means what is published reaches client unmodified.
	// Only the concrete business can explain this event.
	Evt                  string   `protobuf:"bytes,1,opt,name=evt,proto3" json:"evt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPush) Reset()         { *m = ServerPush{} }
func (m *ServerPush) String() string { return proto.CompactTextString(m) }
func (*ServerPush) ProtoMessage()    {}
func (*ServerPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac08d4044ac8a660, []int{13}
}

func (m *ServerPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPush.Unmarshal(m, b)
}
func (m *ServerPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPush.Marshal(b, m, deterministic)
}
func (m *ServerPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPush.Merge(m, src)
}
func (m *ServerPush) XXX_Size() int {
	return xxx_messageInfo_ServerPush.Size(m)
}
func (m *ServerPush) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPush.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPush proto.InternalMessageInfo

func (m *ServerPush) GetEvt() string {
	if m != nil {
		return m.Evt
	}
	return ""
}

func init() {
	proto.RegisterEnum("comet.Packet", Packet_name, Packet_value)
	proto.RegisterType((*PublishReq)(nil), "comet.PublishReq")
	proto.RegisterType((*PublishRes)(nil), "comet.PublishRes")
	proto.RegisterType((*BroadcastReq)(nil), "comet.BroadcastReq")
	proto.RegisterType((*BroadcastRes)(nil), "comet.BroadcastRes")
	proto.RegisterType((*DumpSessionReq)(nil), "comet.DumpSessionReq")
	proto.RegisterType((*DumpSessionRes)(nil), "comet.DumpSessionRes")
	proto.RegisterType((*Room)(nil), "comet.Room")
	proto.RegisterType((*Session)(nil), "comet.Session")
	proto.RegisterType((*Uplink)(nil), "comet.Uplink")
	proto.RegisterType((*Downlink)(nil), "comet.Downlink")
	proto.RegisterType((*Heartbeat)(nil), "comet.Heartbeat")
	proto.RegisterType((*Auth)(nil), "comet.Auth")
	proto.RegisterType((*JoinRoom)(nil), "comet.JoinRoom")
	proto.RegisterType((*ServerPush)(nil), "comet.ServerPush")
}

func init() {
	proto.RegisterFile("comet.proto", fileDescriptor_ac08d4044ac8a660)
}

var fileDescriptor_ac08d4044ac8a660 = []byte{
	// 499 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x8e, 0x93, 0x26, 0xe3, 0x12, 0xcc, 0x00, 0x92, 0x15, 0x55, 0xd0, 0x2e, 0x20, 0x45,
	0x1c, 0xd2, 0xca, 0x88, 0x13, 0x5c, 0xfa, 0x71, 0x08, 0x3d, 0x40, 0xe4, 0x90, 0x03, 0x47, 0x3b,
	0x5d, 0xc9, 0x26, 0x89, 0xd7, 0xdd, 0x5d, 0xa7, 0xe2, 0x77, 0xf0, 0xfb, 0xf8, 0x2f, 0x68, 0xd7,
	0xbb, 0x71, 0xda, 0xfa, 0xc8, 0x6d, 0xe7, 0xbd, 0x99, 0xb7, 0x33, 0xcf, 0x3b, 0x06, 0x7f, 0xc9,
	0x36, 0x54, 0x4e, 0x4a, 0xce, 0x24, 0xc3, 0xae, 0x0e, 0xc8, 0x19, 0xc0, 0xac, 0x4a, 0xd7, 0xb9,
	0xc8, 0x62, 0x7a, 0x8b, 0x01, 0x74, 0xaa, 0xfc, 0x26, 0x74, 0x8e, 0x9d, 0xf1, 0x20, 0x56, 0x47,
	0x85, 0xd0, 0xad, 0x0c, 0xdd, 0x1a, 0xa1, 0x5b, 0x49, 0x0e, 0xf7, 0x2a, 0x04, 0x89, 0xe0, 0xf0,
	0x82, 0xb3, 0xe4, 0x66, 0x99, 0x08, 0x69, 0x14, 0x78, 0xa3, 0xc0, 0x5b, 0x15, 0x86, 0xf7, 0x6a,
	0x04, 0x09, 0x60, 0x78, 0x55, 0x6d, 0xca, 0x39, 0x15, 0x22, 0x67, 0x45, 0x4c, 0x6f, 0xc9, 0xcf,
	0x07, 0x88, 0xc0, 0x77, 0xd0, 0xbd, 0x63, 0x7c, 0xad, 0x94, 0x3b, 0x63, 0x3f, 0x1a, 0x4e, 0xea,
	0x59, 0x6c, 0x46, 0x4d, 0xe2, 0x09, 0x74, 0x39, 0x63, 0x1b, 0x11, 0xba, 0x3a, 0xcb, 0x37, 0x59,
	0x31, 0x63, 0x9b, 0xb8, 0x66, 0xc8, 0x17, 0xf0, 0x54, 0xd8, 0xd2, 0x28, 0x01, 0x4f, 0xa5, 0x98,
	0xda, 0x87, 0x37, 0x68, 0x8e, 0x5c, 0xc2, 0x81, 0x01, 0xda, 0xbd, 0x52, 0x92, 0x6e, 0x23, 0xf9,
	0x12, 0xba, 0x69, 0xce, 0x65, 0x16, 0x76, 0x34, 0x56, 0x07, 0xe4, 0x8f, 0x03, 0xbd, 0x45, 0xb9,
	0xce, 0x8b, 0x15, 0x9e, 0x80, 0x27, 0x7f, 0x97, 0x54, 0xab, 0x0c, 0xa3, 0xa7, 0xe6, 0xce, 0x59,
	0xb2, 0x5c, 0x51, 0x19, 0x6b, 0x0a, 0x8f, 0xc1, 0xcd, 0x52, 0x2d, 0xea, 0x47, 0x81, 0x49, 0x98,
	0xd2, 0x84, 0xcb, 0x94, 0x26, 0x32, 0x76, 0xb3, 0x14, 0xdf, 0x80, 0x97, 0x54, 0xe6, 0x92, 0x66,
	0xe8, 0xf3, 0x4a, 0x66, 0xb1, 0x26, 0xf0, 0x2d, 0x78, 0xbf, 0x58, 0x5e, 0x84, 0x9e, 0x4e, 0x78,
	0x66, 0x12, 0xae, 0x59, 0x5e, 0x68, 0x67, 0x34, 0x49, 0xb6, 0xd0, 0xbf, 0x62, 0x77, 0xc5, 0xff,
	0x6b, 0xeb, 0x3d, 0x78, 0x65, 0x25, 0x6c, 0x5b, 0xcf, 0x77, 0x7e, 0xf2, 0x2d, 0xe5, 0xb3, 0x4a,
	0x64, 0xb1, 0xa6, 0x89, 0x0f, 0x83, 0x5d, 0x1d, 0x39, 0x02, 0x4f, 0xf5, 0xad, 0x8c, 0x93, 0x6c,
	0x45, 0x0b, 0x63, 0x6f, 0x1d, 0x90, 0x23, 0xe8, 0xdb, 0xa6, 0x1f, 0x7f, 0x3f, 0xf2, 0x1a, 0xa0,
	0x11, 0xb7, 0xcf, 0xce, 0xd9, 0x3d, 0xbb, 0x0f, 0x13, 0xe8, 0xd5, 0x13, 0x60, 0x0f, 0xdc, 0xe9,
	0x45, 0xf0, 0x04, 0xfb, 0xe0, 0x9d, 0x2f, 0x7e, 0x4c, 0x03, 0x47, 0x9d, 0xae, 0xbf, 0x7f, 0xfd,
	0x16, 0xb8, 0xea, 0x34, 0x5b, 0xcc, 0xa7, 0x41, 0x27, 0xfa, 0xeb, 0x40, 0xf7, 0x52, 0xf5, 0x8c,
	0xa7, 0x30, 0x98, 0x57, 0xa9, 0x58, 0xf2, 0x3c, 0xa5, 0x68, 0xdd, 0xa8, 0xbf, 0xe0, 0xc8, 0xba,
	0x69, 0xbd, 0x1b, 0x3b, 0x67, 0x0e, 0x9e, 0xc2, 0x81, 0xd9, 0x11, 0xb4, 0x73, 0x37, 0x5b, 0x36,
	0x7a, 0x04, 0x09, 0xfc, 0x04, 0x83, 0xdd, 0x4a, 0xe0, 0x0b, 0xc3, 0xef, 0x2f, 0xd6, 0xa8, 0x05,
	0x14, 0xf8, 0x19, 0xfc, 0xbd, 0x3d, 0xc1, 0x57, 0xb6, 0x97, 0x7b, 0xdb, 0x34, 0x6a, 0x85, 0x45,
	0xda, 0xd3, 0x3f, 0x82, 0x8f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xdb, 0x4d, 0x1a, 0x17,
	0x04, 0x00, 0x00,
}
