// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

package catalog

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{0}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

type ListRes struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListRes) Reset()         { *m = ListRes{} }
func (m *ListRes) String() string { return proto.CompactTextString(m) }
func (*ListRes) ProtoMessage()    {}
func (*ListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{1}
}

func (m *ListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRes.Unmarshal(m, b)
}
func (m *ListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRes.Marshal(b, m, deterministic)
}
func (m *ListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRes.Merge(m, src)
}
func (m *ListRes) XXX_Size() int {
	return xxx_messageInfo_ListRes.Size(m)
}
func (m *ListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListRes proto.InternalMessageInfo

func (m *ListRes) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCent            int32    `protobuf:"varint,3,opt,name=price_cent,json=priceCent,proto3" json:"price_cent,omitempty"`
	SnapshotId           uint64   `protobuf:"varint,1001,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,1002,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,1003,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,1004,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Operator             string   `protobuf:"bytes,1005,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPriceCent() int32 {
	if m != nil {
		return m.PriceCent
	}
	return 0
}

func (m *Product) GetSnapshotId() uint64 {
	if m != nil {
		return m.SnapshotId
	}
	return 0
}

func (m *Product) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Product) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Product) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

func (m *Product) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type SetReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReq) Reset()         { *m = SetReq{} }
func (m *SetReq) String() string { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()    {}
func (*SetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{3}
}

func (m *SetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReq.Unmarshal(m, b)
}
func (m *SetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReq.Marshal(b, m, deterministic)
}
func (m *SetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReq.Merge(m, src)
}
func (m *SetReq) XXX_Size() int {
	return xxx_messageInfo_SetReq.Size(m)
}
func (m *SetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReq proto.InternalMessageInfo

func (m *SetReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type SetRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRes) Reset()         { *m = SetRes{} }
func (m *SetRes) String() string { return proto.CompactTextString(m) }
func (*SetRes) ProtoMessage()    {}
func (*SetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{4}
}

func (m *SetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRes.Unmarshal(m, b)
}
func (m *SetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRes.Marshal(b, m, deterministic)
}
func (m *SetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRes.Merge(m, src)
}
func (m *SetRes) XXX_Size() int {
	return xxx_messageInfo_SetRes.Size(m)
}
func (m *SetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRes.DiscardUnknown(m)
}

var xxx_messageInfo_SetRes proto.InternalMessageInfo

type DeleteReq struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{5}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type DeleteRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRes) Reset()         { *m = DeleteRes{} }
func (m *DeleteRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()    {}
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0abbfcf058acdf89, []int{6}
}

func (m *DeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRes.Unmarshal(m, b)
}
func (m *DeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRes.Marshal(b, m, deterministic)
}
func (m *DeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRes.Merge(m, src)
}
func (m *DeleteRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRes.Size(m)
}
func (m *DeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListReq)(nil), "catalog.ListReq")
	proto.RegisterType((*ListRes)(nil), "catalog.ListRes")
	proto.RegisterType((*Product)(nil), "catalog.Product")
	proto.RegisterType((*SetReq)(nil), "catalog.SetReq")
	proto.RegisterType((*SetRes)(nil), "catalog.SetRes")
	proto.RegisterType((*DeleteReq)(nil), "catalog.DeleteReq")
	proto.RegisterType((*DeleteRes)(nil), "catalog.DeleteRes")
}

func init() {
	proto.RegisterFile("catalog.proto", fileDescriptor_0abbfcf058acdf89)
}

var fileDescriptor_0abbfcf058acdf89 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x87, 0xc9, 0x3a, 0x97, 0xf5, 0x0c, 0xff, 0x70, 0xae, 0xc2, 0x44, 0x29, 0xb9, 0xb1, 0x14,
	0x19, 0x32, 0x05, 0xaf, 0xc7, 0xbc, 0x19, 0x78, 0x21, 0xdd, 0x03, 0x94, 0xd8, 0x04, 0x2d, 0xcc,
	0xa6, 0x36, 0xd9, 0x7b, 0xf8, 0x9a, 0x3a, 0x7d, 0x07, 0x69, 0x9a, 0x76, 0x30, 0xbd, 0x4b, 0xbf,
	0xef, 0xf4, 0x9c, 0xd3, 0x5f, 0x0a, 0xc7, 0xb9, 0xb0, 0x62, 0xa3, 0x5f, 0x66, 0x55, 0xad, 0xad,
	0x46, 0xea, 0x1f, 0x79, 0x08, 0xf4, 0xb1, 0x30, 0x36, 0x55, 0xef, 0xfc, 0xbe, 0x3b, 0x1a, 0xbc,
	0x86, 0x71, 0x55, 0x6b, 0xb9, 0xcd, 0xad, 0x61, 0x24, 0x0a, 0xe2, 0xc9, 0xfc, 0x6c, 0xd6, 0x35,
	0x78, 0x6a, 0x45, 0xda, 0x57, 0xf0, 0x1d, 0x01, 0xea, 0x29, 0x9e, 0xc0, 0xa0, 0x90, 0x8c, 0x44,
	0x24, 0x0e, 0xd3, 0x41, 0x21, 0x11, 0x61, 0x58, 0x8a, 0x37, 0xc5, 0x06, 0x8e, 0xb8, 0x33, 0x5e,
	0x00, 0x54, 0x75, 0x91, 0xab, 0x2c, 0x57, 0xa5, 0x65, 0x41, 0x44, 0xe2, 0xa3, 0x34, 0x74, 0x64,
	0xa9, 0x4a, 0x8b, 0x11, 0x4c, 0x4c, 0x29, 0x2a, 0xf3, 0xaa, 0x6d, 0x56, 0x48, 0xf6, 0x49, 0x23,
	0x12, 0x0f, 0x53, 0xe8, 0xd8, 0x4a, 0xe2, 0x25, 0x40, 0x5e, 0x2b, 0x61, 0x95, 0xcc, 0x84, 0x65,
	0x5f, 0x4d, 0x41, 0x90, 0x86, 0x1e, 0x2d, 0x6c, 0xe3, 0xb7, 0x95, 0xec, 0xfc, 0xce, 0x7b, 0x8f,
	0x5a, 0x2f, 0xd5, 0x46, 0x79, 0xff, 0xed, 0xbd, 0x47, 0x0b, 0x8b, 0xe7, 0x30, 0xd6, 0x95, 0xaa,
	0x85, 0xd5, 0x35, 0xfb, 0xa1, 0x6e, 0xf3, 0x1e, 0xf0, 0x3b, 0x18, 0xad, 0x55, 0x13, 0x18, 0x26,
	0x40, 0x7d, 0x06, 0xee, 0x83, 0xff, 0x0b, 0xa9, 0x2b, 0xe0, 0x63, 0xff, 0x96, 0xe1, 0x09, 0x84,
	0x0f, 0x6e, 0x52, 0xd3, 0xc2, 0x45, 0xe1, 0x2a, 0xb2, 0x3e, 0xb6, 0xd0, 0x93, 0x95, 0xe4, 0x93,
	0x7d, 0xad, 0x99, 0x7f, 0x10, 0xa0, 0xcb, 0xb6, 0x3f, 0x26, 0x30, 0x6c, 0xee, 0x0a, 0xf7, 0x13,
	0xfd, 0x2d, 0x4e, 0x0f, 0x89, 0xc1, 0x2b, 0x08, 0xd6, 0xca, 0xe2, 0x69, 0x2f, 0xda, 0xf5, 0xa7,
	0x07, 0xc0, 0xe0, 0x0d, 0x8c, 0xda, 0x69, 0x88, 0xbd, 0xea, 0x57, 0x9d, 0xfe, 0x65, 0xe6, 0x79,
	0xe4, 0xfe, 0xa6, 0xdb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xae, 0x2f, 0x4e, 0x17, 0x5e, 0x02,
	0x00, 0x00,
}
