// Code generated by protoc-gen-go. DO NOT EDIT.
// source: liveuser.proto

package liveuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserReq struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{0}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

type AddUserRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRes) Reset()         { *m = AddUserRes{} }
func (m *AddUserRes) String() string { return proto.CompactTextString(m) }
func (*AddUserRes) ProtoMessage()    {}
func (*AddUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{1}
}

func (m *AddUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRes.Unmarshal(m, b)
}
func (m *AddUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRes.Marshal(b, m, deterministic)
}
func (m *AddUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRes.Merge(m, src)
}
func (m *AddUserRes) XXX_Size() int {
	return xxx_messageInfo_AddUserRes.Size(m)
}
func (m *AddUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRes proto.InternalMessageInfo

type QueryUserReq struct {
	Uids                 []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserReq) Reset()         { *m = QueryUserReq{} }
func (m *QueryUserReq) String() string { return proto.CompactTextString(m) }
func (*QueryUserReq) ProtoMessage()    {}
func (*QueryUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{2}
}

func (m *QueryUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserReq.Unmarshal(m, b)
}
func (m *QueryUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserReq.Marshal(b, m, deterministic)
}
func (m *QueryUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserReq.Merge(m, src)
}
func (m *QueryUserReq) XXX_Size() int {
	return xxx_messageInfo_QueryUserReq.Size(m)
}
func (m *QueryUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserReq proto.InternalMessageInfo

func (m *QueryUserReq) GetUids() []string {
	if m != nil {
		return m.Uids
	}
	return nil
}

type QueryUserRes struct {
	Users                []*UserRecord `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryUserRes) Reset()         { *m = QueryUserRes{} }
func (m *QueryUserRes) String() string { return proto.CompactTextString(m) }
func (*QueryUserRes) ProtoMessage()    {}
func (*QueryUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{3}
}

func (m *QueryUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRes.Unmarshal(m, b)
}
func (m *QueryUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRes.Marshal(b, m, deterministic)
}
func (m *QueryUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRes.Merge(m, src)
}
func (m *QueryUserRes) XXX_Size() int {
	return xxx_messageInfo_QueryUserRes.Size(m)
}
func (m *QueryUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRes proto.InternalMessageInfo

func (m *QueryUserRes) GetUsers() []*UserRecord {
	if m != nil {
		return m.Users
	}
	return nil
}

// UserRecord 是用户信息
type UserRecord struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Agent                string   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	UpdateAt             string   `protobuf:"bytes,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRecord) Reset()         { *m = UserRecord{} }
func (m *UserRecord) String() string { return proto.CompactTextString(m) }
func (*UserRecord) ProtoMessage()    {}
func (*UserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{4}
}

func (m *UserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRecord.Unmarshal(m, b)
}
func (m *UserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRecord.Marshal(b, m, deterministic)
}
func (m *UserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRecord.Merge(m, src)
}
func (m *UserRecord) XXX_Size() int {
	return xxx_messageInfo_UserRecord.Size(m)
}
func (m *UserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UserRecord proto.InternalMessageInfo

func (m *UserRecord) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRecord) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *UserRecord) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *UserRecord) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserReq)(nil), "liveuser.AddUserReq")
	proto.RegisterType((*AddUserRes)(nil), "liveuser.AddUserRes")
	proto.RegisterType((*QueryUserReq)(nil), "liveuser.QueryUserReq")
	proto.RegisterType((*QueryUserRes)(nil), "liveuser.QueryUserRes")
	proto.RegisterType((*UserRecord)(nil), "liveuser.UserRecord")
}

func init() {
	proto.RegisterFile("liveuser.proto", fileDescriptor_6125f2c4dfd0d26d)
}

var fileDescriptor_6125f2c4dfd0d26d = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x89, 0x49, 0x6a, 0x33, 0x16, 0x91, 0xa1, 0x94, 0xa5, 0x5e, 0xca, 0x9e, 0x82, 0x87,
	0x1e, 0x2a, 0x7a, 0xd0, 0x53, 0x1f, 0xc1, 0x05, 0xcf, 0xb2, 0xba, 0x83, 0x04, 0xb4, 0xa9, 0xfb,
	0xa7, 0xa0, 0xe0, 0xbb, 0xcb, 0xce, 0xb6, 0x4d, 0x84, 0xf4, 0x36, 0xf3, 0xdb, 0x6f, 0xe6, 0x9b,
	0x99, 0x85, 0xcb, 0x8f, 0x66, 0x47, 0xc1, 0x91, 0x5d, 0x6e, 0x6d, 0xeb, 0x5b, 0x1c, 0x1f, 0x72,
	0x79, 0x0f, 0xb0, 0x36, 0xe6, 0xd9, 0x91, 0x55, 0xf4, 0x85, 0x35, 0x14, 0x91, 0x8a, 0x6c, 0x91,
	0xd5, 0x17, 0xab, 0xe9, 0xf2, 0x58, 0x96, 0x04, 0x6f, 0xad, 0x35, 0x8a, 0x15, 0x72, 0xd2, 0xab,
	0x73, 0x52, 0xc2, 0xe4, 0x29, 0x90, 0xfd, 0x3e, 0xf4, 0x41, 0x28, 0x42, 0x63, 0x9c, 0xc8, 0x16,
	0x79, 0x5d, 0x29, 0x8e, 0xe5, 0xc3, 0x3f, 0x8d, 0xc3, 0x1b, 0x28, 0x63, 0xa7, 0x24, 0x3a, 0x65,
	0x96, 0x24, 0xf2, 0x17, 0xa0, 0x83, 0x78, 0x05, 0x79, 0x68, 0x0c, 0x0f, 0x59, 0xa9, 0x18, 0x46,
	0xbf, 0x8d, 0xfe, 0x24, 0x71, 0xc6, 0x88, 0x63, 0x9c, 0x42, 0xa9, 0xdf, 0x69, 0xe3, 0x45, 0xce,
	0x30, 0x25, 0x78, 0x0d, 0x55, 0xd8, 0x1a, 0xed, 0xe9, 0x45, 0x7b, 0x51, 0xf0, 0xcb, 0x38, 0x81,
	0xb5, 0xc7, 0x19, 0x8c, 0xf4, 0x4e, 0x7b, 0x6d, 0x45, 0xc9, 0x2f, 0xfb, 0x6c, 0xf5, 0x03, 0x45,
	0xb4, 0xc7, 0x3b, 0x38, 0xdf, 0x2f, 0x8d, 0xbd, 0x71, 0xbb, 0xfb, 0xcd, 0x87, 0xa8, 0xc3, 0x47,
	0xa8, 0x8e, 0x9b, 0xe3, 0xac, 0x93, 0xf4, 0x4f, 0x36, 0x1f, 0xe6, 0xee, 0x75, 0xc4, 0x3f, 0x76,
	0xfb, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xed, 0x69, 0xb3, 0xc3, 0x01, 0x00, 0x00,
}
