// Code generated by protoc-gen-go. DO NOT EDIT.
// source: liveuser.proto

package liveuser

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserReq struct {
	User                 *UserRecord `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{0}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetUser() *UserRecord {
	if m != nil {
		return m.User
	}
	return nil
}

type AddUserRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRes) Reset()         { *m = AddUserRes{} }
func (m *AddUserRes) String() string { return proto.CompactTextString(m) }
func (*AddUserRes) ProtoMessage()    {}
func (*AddUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{1}
}

func (m *AddUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRes.Unmarshal(m, b)
}
func (m *AddUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRes.Marshal(b, m, deterministic)
}
func (m *AddUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRes.Merge(m, src)
}
func (m *AddUserRes) XXX_Size() int {
	return xxx_messageInfo_AddUserRes.Size(m)
}
func (m *AddUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRes proto.InternalMessageInfo

type QueryUserReq struct {
	Uids                 []string `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryUserReq) Reset()         { *m = QueryUserReq{} }
func (m *QueryUserReq) String() string { return proto.CompactTextString(m) }
func (*QueryUserReq) ProtoMessage()    {}
func (*QueryUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{2}
}

func (m *QueryUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserReq.Unmarshal(m, b)
}
func (m *QueryUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserReq.Marshal(b, m, deterministic)
}
func (m *QueryUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserReq.Merge(m, src)
}
func (m *QueryUserReq) XXX_Size() int {
	return xxx_messageInfo_QueryUserReq.Size(m)
}
func (m *QueryUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserReq proto.InternalMessageInfo

func (m *QueryUserReq) GetUids() []string {
	if m != nil {
		return m.Uids
	}
	return nil
}

type QueryUserRes struct {
	Users                []*UserRecord `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryUserRes) Reset()         { *m = QueryUserRes{} }
func (m *QueryUserRes) String() string { return proto.CompactTextString(m) }
func (*QueryUserRes) ProtoMessage()    {}
func (*QueryUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{3}
}

func (m *QueryUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryUserRes.Unmarshal(m, b)
}
func (m *QueryUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryUserRes.Marshal(b, m, deterministic)
}
func (m *QueryUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserRes.Merge(m, src)
}
func (m *QueryUserRes) XXX_Size() int {
	return xxx_messageInfo_QueryUserRes.Size(m)
}
func (m *QueryUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserRes proto.InternalMessageInfo

func (m *QueryUserRes) GetUsers() []*UserRecord {
	if m != nil {
		return m.Users
	}
	return nil
}

// UserRecord 是用户信息
type UserRecord struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Agent                string   `protobuf:"bytes,3,opt,name=agent,proto3" json:"agent,omitempty"`
	UpdateAt             string   `protobuf:"bytes,4,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	Avatar               string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRecord) Reset()         { *m = UserRecord{} }
func (m *UserRecord) String() string { return proto.CompactTextString(m) }
func (*UserRecord) ProtoMessage()    {}
func (*UserRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{4}
}

func (m *UserRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRecord.Unmarshal(m, b)
}
func (m *UserRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRecord.Marshal(b, m, deterministic)
}
func (m *UserRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRecord.Merge(m, src)
}
func (m *UserRecord) XXX_Size() int {
	return xxx_messageInfo_UserRecord.Size(m)
}
func (m *UserRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRecord.DiscardUnknown(m)
}

var xxx_messageInfo_UserRecord proto.InternalMessageInfo

func (m *UserRecord) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRecord) GetAgent() string {
	if m != nil {
		return m.Agent
	}
	return ""
}

func (m *UserRecord) GetUpdateAt() string {
	if m != nil {
		return m.UpdateAt
	}
	return ""
}

func (m *UserRecord) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type LoginReq struct {
	// 用户登录凭证（有效期五分钟）。开发者需要在开发者服务器后台调用 auth.code2Session，
	// 使用 code 换取 openid、unionid、session_key 等信息
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{5}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type LoginRes struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Expiry               int64    `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{6}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginRes) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type RefreshTokenReq struct {
	RefreshToken         string   `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{7}
}

func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(m, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRes) Reset()         { *m = RefreshTokenRes{} }
func (m *RefreshTokenRes) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRes) ProtoMessage()    {}
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6125f2c4dfd0d26d, []int{8}
}

func (m *RefreshTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRes.Unmarshal(m, b)
}
func (m *RefreshTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRes.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRes.Merge(m, src)
}
func (m *RefreshTokenRes) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRes.Size(m)
}
func (m *RefreshTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRes proto.InternalMessageInfo

func (m *RefreshTokenRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserReq)(nil), "liveuser.AddUserReq")
	proto.RegisterType((*AddUserRes)(nil), "liveuser.AddUserRes")
	proto.RegisterType((*QueryUserReq)(nil), "liveuser.QueryUserReq")
	proto.RegisterType((*QueryUserRes)(nil), "liveuser.QueryUserRes")
	proto.RegisterType((*UserRecord)(nil), "liveuser.UserRecord")
	proto.RegisterType((*LoginReq)(nil), "liveuser.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "liveuser.LoginRes")
	proto.RegisterType((*RefreshTokenReq)(nil), "liveuser.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenRes)(nil), "liveuser.RefreshTokenRes")
}

func init() {
	proto.RegisterFile("liveuser.proto", fileDescriptor_6125f2c4dfd0d26d)
}

var fileDescriptor_6125f2c4dfd0d26d = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcb, 0x4f, 0xfa, 0x40,
	0x10, 0xc7, 0x53, 0xda, 0xf2, 0xa3, 0x43, 0x7f, 0x6a, 0x26, 0x84, 0xd4, 0x9a, 0x18, 0x5c, 0x2f,
	0xc4, 0x03, 0x26, 0xa8, 0x1c, 0xf4, 0x44, 0xe2, 0xd1, 0x8b, 0x8d, 0xc6, 0x23, 0x59, 0xdb, 0x15,
	0xeb, 0xa3, 0xc5, 0xdd, 0x96, 0x80, 0xc6, 0xff, 0xdd, 0x74, 0x77, 0xa1, 0x95, 0x47, 0xe2, 0x6d,
	0xe6, 0x3b, 0x9f, 0x79, 0x74, 0x66, 0x0b, 0x3b, 0x6f, 0xf1, 0x94, 0xe5, 0x82, 0xf1, 0xde, 0x84,
	0xa7, 0x59, 0x8a, 0x8d, 0x85, 0x4f, 0x06, 0x00, 0xc3, 0x28, 0xba, 0x17, 0x8c, 0x07, 0xec, 0x03,
	0xbb, 0x60, 0x15, 0xaa, 0x67, 0x74, 0x8c, 0x6e, 0xb3, 0xdf, 0xea, 0x2d, 0xd3, 0x14, 0x10, 0xa6,
	0x3c, 0x0a, 0x24, 0x41, 0xdc, 0x4a, 0x9e, 0x20, 0x04, 0xdc, 0xdb, 0x9c, 0xf1, 0xf9, 0xa2, 0x0e,
	0x82, 0x95, 0xc7, 0x91, 0xf0, 0x8c, 0x8e, 0xd9, 0x75, 0x02, 0x69, 0x93, 0xcb, 0x5f, 0x8c, 0xc0,
	0x13, 0xb0, 0x8b, 0x4a, 0x0a, 0xda, 0xd6, 0x4c, 0x21, 0xe4, 0x1b, 0xa0, 0x14, 0x71, 0x0f, 0xcc,
	0x3c, 0x8e, 0xe4, 0x90, 0x4e, 0x50, 0x98, 0x45, 0xbf, 0x84, 0xbe, 0x33, 0xaf, 0x26, 0x25, 0x69,
	0x63, 0x0b, 0x6c, 0x3a, 0x66, 0x49, 0xe6, 0x99, 0x52, 0x54, 0x0e, 0x1e, 0x80, 0x93, 0x4f, 0x22,
	0x9a, 0xb1, 0x11, 0xcd, 0x3c, 0x4b, 0x46, 0x1a, 0x4a, 0x18, 0x66, 0xd8, 0x86, 0x3a, 0x9d, 0xd2,
	0x8c, 0x72, 0xcf, 0x96, 0x11, 0xed, 0x91, 0x43, 0x68, 0xdc, 0xa4, 0xe3, 0x38, 0xd1, 0x9f, 0x16,
	0xa6, 0x11, 0xd3, 0xdd, 0xa5, 0x4d, 0x5e, 0x96, 0x71, 0x81, 0x47, 0xe0, 0xd2, 0x30, 0x64, 0x42,
	0x8c, 0xb2, 0xf4, 0x95, 0x25, 0x9a, 0x6b, 0x2a, 0xed, 0xae, 0x90, 0xf0, 0x18, 0xfe, 0x73, 0xf6,
	0xc4, 0x99, 0x78, 0xd6, 0x8c, 0x1a, 0xdb, 0xd5, 0xa2, 0x82, 0xda, 0x50, 0x67, 0xb3, 0x49, 0xcc,
	0xe7, 0x72, 0x7e, 0x33, 0xd0, 0x1e, 0x19, 0xc0, 0x6e, 0x50, 0xe1, 0x8a, 0x91, 0xd6, 0xea, 0x19,
	0xeb, 0xf5, 0xc8, 0xf9, 0x6a, 0xde, 0x5f, 0x46, 0xed, 0x7f, 0x82, 0x55, 0x2c, 0x1e, 0x2f, 0xe0,
	0x9f, 0x3e, 0x37, 0x56, 0x0e, 0x55, 0xbe, 0x1c, 0x7f, 0x93, 0x2a, 0xf0, 0x0a, 0x9c, 0xe5, 0xcd,
	0xb1, 0x5d, 0x22, 0xd5, 0xc7, 0xe2, 0x6f, 0xd6, 0x45, 0xff, 0x0b, 0x6a, 0x0f, 0x33, 0x3c, 0x05,
	0x5b, 0xee, 0x16, 0xb1, 0xc4, 0x16, 0xc7, 0xf0, 0xd7, 0x35, 0x81, 0xd7, 0xe0, 0x56, 0x3f, 0x14,
	0xf7, 0x4b, 0x66, 0x65, 0x71, 0xfe, 0xd6, 0x90, 0x78, 0xac, 0xcb, 0x1f, 0xe5, 0xec, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x74, 0xd1, 0x99, 0x37, 0x3a, 0x03, 0x00, 0x00,
}
